/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Address Book
 * The Address Book API description
 * OpenAPI spec version: 1.0
 */

export interface Contact {
  _id: string;
  /** The contact's name */
  name: string;
  /** The contact's phone number */
  phone: string;
  createdAt: string;
  updatedAt: string;
}
